### ISSUE TITLE
'Grammar' object has no attribute 'all_terminals'

### ISSUE THREAD

**Issue by aleberans** [let-unimi/liblet#1]
Nell' handout 5 nella cella 6 viene invocato all_terminals ma esce questo errore. Ho provato a invocarlo pure nel playground ma non va lo stesso.

**Comment by mapio** [comment]
Il link agli handout nel diario delle lezioni è "versionato" e legato alla versione vista in classe. Può capitare che riveda il codice per adeguarlo alle nuove versioni della libreria. Se osserva la versione del branch master https://github.com/let-unimi/handouts/blob/master/L05.ipynb noterà che nella cella 6 viene usata l'espressione `set(derivation.sentential_form()) <= G.T` invece del metodo `all_terminals` che è stato rimosso, proprio perché l'espressione insiemistica secondo me risulta più comprensibile.
