### ISSUE TITLE
Attribute Serialization

### ISSUE THREAD

**Issue by RiccardoRaffini** [let-unimi/liblet#10]
If you define an object of the `AnnotatedTreeWalker` class that makes use of attributes within the registered functions, saving the _ATW_ object with the `save `method does not save the attributes used, as in the case of the following example:

~~~python
from liblet import AnnotatedTreeWalker, Tree

tree = Tree({'name': 'test'})

test_atw = AnnotatedTreeWalker('name')
@test_atw.register
def test(visit, ast):
    test_atw.VAR = 5
    print(test_atw.VAR)
    print(3)

test_atw(tree) # out: 5 3

test_atw.save('test.atw')
test_atw = AnnotatedTreeWalker.load('test.atw')

test_atw(tree) # out: exception
~~~

By running the above code, an error is raised:

`NameError: name 'test_atw' is not defined`

**Comment by mapio** [comment]
Serializing attributes is in general not possible (some of them can be impossible to serialize). It should be simple to keep track of added attributes and re-add them after loading. Or one can extend the class and provide serialization for the added attributes.
